---
language: node_js
node_js:
  - "7.6"
  - "8"
  - "9"
before_script:
  - git config --global user.email "davewasmer@gmail.com"
  - git config --global user.name "Dave Wasmer"
sudo: false
cache:
  directories:
    - node_modules
